@isTest
public class FutureAccountsContactTest {
	@isTest
    private static void testCountContacts() {
        List<Account> accList = new List<Account>();

        for(Integer i=0 ; i<300 ; i++) {
            accList.add(new Account(Name = 'Test ' + i));
        }
        
        Test.startTest();
        insert accList;
        
        List<Contact> conList = new List<Contact>();
        List<Id> accIds = new List<Id>();
        
        for(Account acc : accList) {
            Contact con = new Contact(firstName = 'Test', lastName = acc.Name, AccountId = acc.Id);
            conList.add(con);
        }
        
        insert conList;
        
        FutureAccountsContact.countContacts(accIds);
        
        Test.stopTest();
        
        List<Account> accs = [SELECT Id, Total_Contacts__c FROM Account];
        
        System.assertEquals(1,accs[0].Total_Contacts__c,'Contacts are not counted successfully!');
    }
}